### ISSUE TITLE
fine-tuning code for recognition task

### ISSUE THREAD

**Issue by Nidhi-kumari** [GewelsJI/MVLT#1]
Hi, 
This work looks interesting.
Could you please provide the fine-tuning code for the recognition task (category/sub-category recognition) for the custom dataset?

**Comment by GewelsJI** [comment]
Hi,

I am a little bit busy these days, and I will upload it ASAP. Thank you for your patience.

Best.

**Comment by GewelsJI** [comment]
hi @Nidhi-kumari 

Sorry for the late reply. Just right now, I reorganized the entire repo tree and uploaded [pre-train script](https://github.com/GewelsJI/MVLT/blob/main/scripts_dws/dws_mvlt_exp21.sh) and [fine-tune script](https://github.com/GewelsJI/MVLT/blob/main/scripts_dws/dws_mvlt_ft_exp48.sh). Please pull the latest git repo and then enjoy them again.

Best,
Ge-Peng.
